FROM jenkins/jenkins:lts
 
USER root
 
# Install Docker CLI
RUN apt-get update && apt-get install -y docker.io \
&& rm -rf /var/lib/apt/lists/*
 
# Create docker group if not exists and add jenkins user
RUN groupadd -f docker && usermod -aG docker jenkins
 
USER jenkins
