FROM jenkins/jenkins:lts

USER root

# Install Docker, kubectl, and other tools
RUN apt-get update && \
    apt-get install -y docker.io curl && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    usermod -aG docker jenkins && \
    rm kubectl && \
    apt-get clean

USER jenkins